name: Pylint

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        poetry-version: ["1.3.2"]
        os: ["ubuntu-10.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry ${{ matrix.poetry-version }}
        run: |
          python -m pip install poetry==${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Analyzing the code with pylint
        run: |
          poetry run pylint dbcl
