name: Linting

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.3.2"]
        os: ["ubuntu-18.04"]
        linter-command:
          - poetry run pylint dbcl
          - poetry run black --check --diff .

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry ${{ matrix.poetry-version }}
        run: pipx install poetry==${{ matrix.poetry-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      # - if: ${{ steps.cache-poetry-venv.outputs.cache-hit != 'true' }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Analyzing the code with "${{ matrix.linter-command }}"
        run: |
          ${{ matrix.linter-command }}
